# Generated by Django 3.2 on 2021-05-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Name', models.CharField(max_length=100)),
                ('Genre', models.CharField(choices=[('ROMANCE', 'Romance'), ('ACTION', 'Action'), ('HORROR', 'Horror'), ('THRILLER', 'Thriller'), ('ENTERTAINMENT', 'Entertainment')], max_length=50)),
                ('Directed_By', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Added_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
