# Generated by Django 3.2 on 2021-05-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierater', '0002_alter_rater_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='userid',
            field=models.CharField(default=1, max_length=26, unique=True),
            preserve_default=False,
        ),
    ]
