# Generated by Django 3.2 on 2021-05-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierater', '0003_rater_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='userid',
            field=models.CharField(default=1, max_length=26, unique=True),
        ),
    ]
