# Generated by Django 3.2 on 2021-05-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierater', '0004_alter_rater_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rater',
            name='userid',
        ),
    ]
