# Generated by Django 3.2 on 2021-05-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierater', '0007_remove_rater_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='Rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
    ]
