# Generated by Django 3.2 on 2021-06-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierater', '0009_rater_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rater',
            name='date',
        ),
    ]
